# Generated by Django 4.0.3 on 2022-06-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pathIm',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
